project:
  type: website
  output-dir: docs
  title: "sowiaaron.github.io"


format: 
  html: 
    theme: lux
    toc: true
    lof: true
    code-tools: true
    code-fold: true
    code-annotations: true  
    code-line-numbers: true
    code-overflow: wrap

  pdf: 
    documentclass: scrartcl
    classoption: 
      - landscape
      - twocolumn
      - a4paper
    colorlinks: true
    pdf-enginge: pdflatex
    header-includes:
      - \usepackage{pst-barcode} 
      - \usepackage[babel, german=quotes]{csquotes}
    keep-tex: true
    template: reporting.tex
    
website:
  back-to-top-navigation: true
